### ISSUE TITLE
Prefix error

### ISSUE THREAD

**Issue by kainlighty** [xii69/VelocityStaffChat#1]
![image](https://github.com/xii69/VelocityStaffChat/assets/111251772/34a38c19-83ef-4902-b191-2f5a9b291591)

The prefix from the configuration is not used in the code. I also tried to make changes and send a pull request, but there are no permissions

**Comment by xii69** [comment]
Thank you for reporting this issue, I'll fix it as soon as possible
Also I didn't change anything related to Pull Requests, can you try again or at least provide more information maybe I can open the pull requests.

**Comment by kainlighty** [comment]
> Thank you for reporting this issue, I'll fix it as soon as possible
> 
> Also I didn't change anything related to Pull Requests, can you try again or at least provide more information maybe I can open the pull requests.

Check out the fork on my page. Add LuckPerms support. The code in the project.

**Comment by xii69** [comment]
Fixed in [this release](https://github.com/xii69/VelocityStaffChat/releases/tag/1.2.0), thank you for reporting the problem.
