### ISSUE TITLE
"/vsc" Doesn't work

### ISSUE THREAD

**Issue by At87668** [xii69/VelocityStaffChat#4]
When I type "/vsc", the plugin says I've switched channels, but I still need to prefix it with #, otherwise I can't do channel chat ,only send globally.
Can you fix it?
Thanks.

**Comment by At87668** [comment]
Spigot and Velocity have this bug(only my tested)

**Comment by xii69** [comment]
Hey, thanks for reporting this issue, it seems I've break the command by trying to optimize the plugin, releasing the fix in ~1 hour.

**Comment by xii69** [comment]
The issue has been fixed in [2.1.0 release](https://github.com/xii69/VStaffChat/releases/tag/2.1.0)
